name: Hello World Workflow

on:
  push:
    branches:
      - main  # triggers when you push to main branch

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run hello.py from codes folder
        run: python codes/hello.py
